["protostar.config"]
protostar_version = "0.3.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
race = [
    "src/core/race/race.cairo",
]

basic_car = [
    "src/cars/basic_car/basic_car.cairo",
]

grand_prix = [
    "src/grand_prix/grand_prix.cairo",
]

season = [
    "src/season/season.cairo",
]

[profile.devnet.protostar.deploy]
gateway_url="http://127.0.0.1:5050/"
